### PR TITLE
Add game history to the database

### LINKED ISSUE #52: Add basic history to DB for each game and turn taken

### PR DESCRIPTION
**Pull request by nelspd915**
Adds a game history log to the database.

Fixes #52

### CODE REVIEW

**Comment by nelspd915** [comment]
@Saguuu:
> only thing I see is in reveal cell shouldnt we only add to turn history for valid requests? right now I think it would add an invalid move to the game history

True, I'll move it to the following `if` block so it only fires when the revealCell is legal.

> Also the cell never gets saved to turn data as "revealed" I think because that is applied after everything else, unless thats not an issue

I think that's ok, basically we just want to track which cell was chosen at each turn.

**Review by Saguuu — APPROVED** [review]
👍

**Comment by nelspd915** [comment]
@Saguuu 
Do you know why `$2a$04$` is showing up at the beginning of each `gameId`, am I not using bcrypt quite right?

**Comment by Saguuu** [comment]
> @Saguuu Do you know why `$2a$04$` is showing up at the beginning of each `gameId`, am I not using bcrypt quite right?

I believe that is a product of the salt. Pretty sure its there for comparison purposes, not sure how you'd exclude it.

**Comment by nelspd915** [comment]
> > @Saguuu Do you know why `$2a$04$` is showing up at the beginning of each `gameId`, am I not using bcrypt quite right?
> 
> I believe that is a product of the salt. Pretty sure its there for comparison purposes, not sure how you'd exclude it.

Ok if it's supposed to be there then that's fine

**Comment by nelspd915** [comment]
Oops I missed one commit

**Pull request merged**
