### PR TITLE
Show which team wins

### PR DESCRIPTION
**Pull request by nelspd915**
Display on top banner which team won the game.

### CODE REVIEW

**Review by Saguuu — COMMENTED** [review]
Tested everything and it looks good. Not sure what's going on with that test case though. Don't understand how scores can be undefined ever.

**Comment by nelspd915** [comment]
> Tested everything and it looks good. Not sure what's going on with that test case though. Don't understand how scores can be undefined ever.

The test case was failing since the `codenames-scores` component was not being given any `scores` or `turn` props in the unit test. I added them which fixed it.

**Review by Saguuu — APPROVED** [review]
ah makes sense 🦩 👍

**Comment by nelspd915** [comment]
Oops guess I broke it somehow lol

**Pull request merged**
